== 요청 및 응답

[[요청-URL]]
=== 요청 URL (환경 서브 도메인)

API 요청 URL은 배포 환경에 따라 서브 도메인이 변경될 수 있습니다.

- 개발 환경: `https://dev.capture-cat.com`
- 운영 환경: `https://api.capture-cat.com`

문서는 개발 환경을 기준으로 작성되었지만, 운영 환경에서도 동일한 형식으로 요청할 수 있어요.

[[단일-응답-객체-형식]]
=== 단일 응답 객체 형식

단일 리소스를 조회하거나 생성한 결과를 반환할 때는 다음과 같은 형식이에요. 필요한 데이터만 간결하게 담겨 있어요.

[source,json]
----
{
  "resultType": "SUCCESS",
  "data": "{DATA}"
}
----

==== 필드 설명

* `resultType`: 요청의 결과 상태를 나타내요. 성공 시 `SUCCESS` 값을 가집니다.
* `data`: 요청에 대한 실제 응답 데이터를 포함해요. 요청에 따라 다양한 형식이 될 수 있어요.

==== 예시

[source,json]
----
{
  "resultType": "SUCCESS",
  "data": {
    "id": 123,
    "name": "Example Item"
  }
}
----

[[리스트-응답-객체-형식]]
=== 리스트 응답 객체 형식

복수의 리소스를 조회하는 API는 다음과 같은 형식으로 응답해요. 리스트 외에 페이징 정보 등이 함께 포함될 수 있어요.

[source,json]
----
{
  "resultType": "SUCCESS",
  "data": {
    "hasNext": true,
    "lastCursor": 0,
    "items": []
  }
}
----

==== 필드 설명
* `resultType`: 요청의 결과 상태를 나타내요. 성공 시 `SUCCESS` 값을 가집니다.
* `data`: 요청에 대한 실제 응답 데이터를 포함해요.
  - `hasNext`: 다음 페이지가 있는지 여부를 나타내는 boolean 값입니다.
  - `lastCursor`: 마지막으로 조회된 커서 값입니다. 다음 페이지 요청 시 사용될 수 있어요.
  - `items`: 요청에 대한 실제 데이터 리스트를 포함합니다. 빈 배열일 수도 있어요.

==== 예시
[source,json]
----
{
  "resultType": "SUCCESS",
  "data": {
    "hasNext": true,
    "nextPage": 2,
    "items": [
      {
        "id": 123,
        "name": "Example Item 1"
      },
      {
        "id": 456,
        "name": "Example Item 2"
      }
    ]
  }
}
----

[[페이징-없는-리스트-응답-객체-형식]]
=== 페이징 없는 리스트 응답 객체 형식

페이징 정보 없이 단순히 리스트만 반환하는 경우는 다음과 같은 형식이에요. 데이터가 리스트로 담겨 있어요.

[source,json]
----
{
  "resultType": "SUCCESS",
  "data": []
}
----

==== 필드 설명

* `resultType`: 요청의 결과 상태를 나타내요. 성공 시 `SUCCESS` 값을 가집니다.
* `data`: 요청에 대한 실제 응답 데이터를 포함해요. 이 경우는 단순히 리스트 형태로 데이터가 담겨 있어요.

==== 예시
[source,json]
----
{
    "resultType": "SUCCESS",
    "data": [
        {
            "id": 123,
            "name": "Example Item 1"
        },
        {
            "id": 456,
            "name": "Example Item 2"
        }
    ]
}
----


[[응답-HTTP-상태-코드]]
=== 응답 HTTP 상태 코드

[cols="2,4"]
|===
| HTTP 상태 코드 | 설명

| 200 - OK    | 요청이 성공적으로 처리되었습니다.
| 400 - Bad Request    | 요청을 처리할 수 없습니다. 필수 파라미터를 보내지 않았거나, 파라미터 포맷이 잘못되었을 때 돌아오는 응답입니다. 요청 파라미터를 확인해주세요.
| 401 - Unauthorized | 인증이 필요한 요청입니다. 토큰이 없거나 유효하지 않은 경우에 발생해요. 토큰을 확인해주세요.
| 403 - ForBidden    | 권한이 없는 요청입니다. 해당 리소스에 접근할 권한이 없을 때 발생해요. 권한을 확인해주세요.
| 404 - Not Found   | 요청한 리소스가 존재하지 않습니다. 요청한 API 주소를 다시 한번 확인해보세요.
| 429 - Too Many Requests | 비정상적으로 많은 요청을 보냈습니다. 잠시 후 다시 시도해주세요.
| 500 - Server Error | 서버에서 에러가 발생했습니다.
|===

[[에러-객체-형식]]
=== 에러 객체 형식

API 요청이 실패하면 다음과 같은 형식으로 응답을 반환해요.

[source,json]
----
{
  "resultType": "ERROR",
  "error": {
    "code": "{ERROR_CODE}",
    "message": "{ERROR_MESSAGE}"
  }
}
----

==== 오류 필드 설명

* `resultType`: 요청의 결과 상태를 나타내요. 실패 시 `ERROR` 값을 가집니다.
* `error`: 요청 처리 중 발생한 오류 정보를 포함해요.
- `code`: 오류 코드로, 특정 오류를 식별하는 데 사용됩니다.
- `message`: 오류에 대한 설명 메시지로, 사용자에게 표시됩니다.

==== 오류 예시

[source,json]
----
{
  "resultType": "ERROR",
  "error": {
    "code": "NOT_FOUND_ITEM",
    "message": "아이템을 찾을 수 없어요."
  }
}
----
