create table if not exists users
(
    id                 bigint       not null primary key,
    nickname           varchar(50)  not null,
    email              varchar(50)  not null,
    username           varchar(50)  not null unique,
    password           varchar(70),
    role               varchar(255) not null constraint users_role_check check (role in ('ADMIN', 'PREMIUM_USER', 'USER')),
    tutorial_completed boolean      not null,
    provider           varchar(255),
    social_id          varchar(255),
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null
);

create table if not exists user_social_account
(
    id                 bigint       not null primary key,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null,
    provider           varchar(30)  not null,
    social_id          varchar(100) not null,
    unlink_key         varchar(512),
    user_id            bigint       not null constraint fk998rgv7jn090iyc77f8e1xsnq references users,
    constraint uksj2lqxj8h0xuqf9v1dvtlkegt unique (provider, social_id)
);

create table if not exists refresh_token
(
    id                       bigint not null primary key,
    refresh_token_expiration bigint not null,
    expiration               varchar(255),
    refresh_token            varchar(255),
    username                 varchar(255)
);

create table if not exists withdraw_log
(
    id                   bigint generated by default as identity primary key,
    created_date         timestamp(6) not null,
    last_modified_date   timestamp(6) not null,
    image_cleanup_status varchar(255) not null constraint withdraw_log_image_cleanup_status_check check (image_cleanup_status in ('PENDING', 'DONE', 'FAILED')),
    reason               text,
    user_id              bigint       not null
);

create index if not exists idx_withdraw_log_user_id on withdraw_log (user_id);

create index if not exists idx_withdraw_log_created_date on withdraw_log (created_date);

create index if not exists idx_withdraw_log_cleanup_status on withdraw_log (image_cleanup_status, created_date);

create table if not exists images
(
    id                 bigint generated by default as identity primary key,
    size               bigint,
    file_name          varchar(255),
    file_url           varchar(255),
    capture_date       date,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null,
    user_id            bigint constraint fk13ljqfrfwbyvnsdhihwta8cpr references users
);

create table if not exists tag
(
    id                 bigint generated by default as identity primary key,
    name               varchar(255),
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null
);

create table if not exists image_tag
(
    id                 bigint generated by default as identity primary key,
    image_id           bigint constraint fk6q9wuvp5j846qtqod6xu3gma1 references images,
    tag_id             bigint constraint fk28yowgjl7oksr7dc0wj7f5il references tag,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null
);

create table if not exists bookmark
(
    id       bigint generated by default as identity primary key,
    image_id bigint constraint fkpowbsxsu0qwcon1yoxbsqkw4w references images,
    user_id  bigint constraint fko4vbqvq5trl11d85bqu5kl870 references users
);
