create table if not exists user_tag
(
    id                 bigint generated by default as identity primary key,
    user_id            bigint constraint fk_user_tag_user references users,
    tag_id             bigint constraint fk_user_tag_tag references tag,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null,
    constraint uk_user_tag_user_tag unique (user_id, tag_id)
);
