package com.capturecat.core.support.error;

import org.springframework.boot.logging.LogLevel;
import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ErrorType {

	DEFAULT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCode.EXAMPLE_ERROR, LogLevel.ERROR),
	IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCode.NOT_FOUND_IMAGE, LogLevel.WARN),
	TOO_MANY_TAGS(HttpStatus.BAD_REQUEST, ErrorCode.EXCEED_MAX_TAG_COUNT, LogLevel.WARN),
	INVALID_REQUEST(HttpStatus.BAD_REQUEST, ErrorCode.INVALID_REQUEST, LogLevel.WARN),
	INVALID_DATE_FORMAT(HttpStatus.BAD_REQUEST, ErrorCode.INVALID_DATE_FORMAT, LogLevel.WARN),
	IMAGE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCode.S3_FILE_UPLOAD_FAILED, LogLevel.ERROR),
	IMAGE_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCode.S3_FILE_DELETE_FAILED, LogLevel.ERROR),
	INVALID_IMAGE_FORMAT(HttpStatus.BAD_REQUEST, ErrorCode.INVALID_IMAGE_FORMAT, LogLevel.WARN),
	UPLOAD_METADATA_MISMATCH(HttpStatus.BAD_REQUEST, ErrorCode.UPLOAD_METADATA_MISMATCH, LogLevel.WARN),
	DUPLICATE_TAG_NAMES(HttpStatus.BAD_REQUEST, ErrorCode.DUPLICATE_TAG_NAMES, LogLevel.WARN),
	ALREADY_REGISTERED_TAGS(HttpStatus.BAD_REQUEST, ErrorCode.ALREADY_REGISTERED_TAGS, LogLevel.WARN),
	JOIN_FAIL(HttpStatus.BAD_REQUEST, ErrorCode.ALREADY_EXISTS_USERNAME, LogLevel.WARN),
	LOGIN_FAIL(HttpStatus.BAD_REQUEST, ErrorCode.INVALID_REQUEST, LogLevel.WARN),
	VALIDATION_FAIL(HttpStatus.BAD_REQUEST, ErrorCode.BEAN_VALIDATION_FAIL, LogLevel.WARN),
	INVALID_JWT(HttpStatus.BAD_REQUEST, ErrorCode.BEAN_VALIDATION_FAIL, LogLevel.WARN),
	UNKNOWN_ROLE(HttpStatus.BAD_REQUEST, ErrorCode.UNKNOWN_ROLE, LogLevel.WARN),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCode.NOT_FOUND_USER, LogLevel.WARN),
	ACCESS_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST, ErrorCode.ACCESS_TOKEN_EXPIRED, LogLevel.WARN),
	REFRESH_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST, ErrorCode.REFRESH_TOKEN_EXPIRED, LogLevel.WARN),
	INVALID_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED, ErrorCode.INVALID_ACCESS_TOKEN, LogLevel.WARN),
	INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, ErrorCode.INVALID_REFRESH_TOKEN, LogLevel.WARN),
	IMAGE_ACCESS_DENIED(HttpStatus.FORBIDDEN, ErrorCode.IMAGE_ACCESS_DENIED, LogLevel.WARN),
	TAG_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCode.NOT_FOUND_TAG, LogLevel.WARN),
	IMAGE_TAG_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCode.NOT_FOUND_IMAGE_TAG, LogLevel.WARN),
	BOOKMARK_DUPLICATION(HttpStatus.BAD_REQUEST, ErrorCode.ALREADY_EXISTS_BOOKMARK, LogLevel.WARN),
	INVALID_ID_TOKEN(HttpStatus.UNAUTHORIZED, ErrorCode.INVALID_ID_TOKEN, LogLevel.WARN),
	INVALID_AUTH_TOKEN(HttpStatus.UNAUTHORIZED, ErrorCode.INVALID_AUTH_TOKEN, LogLevel.WARN),
	BOOKMARK_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorCode.NOT_FOUND_BOOKMARK, LogLevel.WARN),
	GENERATE_CLIENT_SECRET_FAIL(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCode.GENERATE_CLIENT_SECRET_FAIL,
		LogLevel.ERROR), UNLINK_SOCIAL_FAIL(HttpStatus.BAD_REQUEST, ErrorCode.UNLINK_SOCIAL_FAIL, LogLevel.WARN),
	FETCH_SOCIAL_TOKEN_FAIL(HttpStatus.BAD_REQUEST, ErrorCode.FETCH_SOCIAL_TOKEN_FAIL, LogLevel.WARN),
	SOCIAL_API_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, ErrorCode.SOCIAL_API_ERROR, LogLevel.WARN);

	private final HttpStatus status;

	private final ErrorCode code;

	private final LogLevel logLevel;

	ErrorType(HttpStatus status, ErrorCode code, LogLevel logLevel) {
		this.status = status;
		this.code = code;
		this.logLevel = logLevel;
	}

}
