server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 60MB

logging:
  level:
    com.capturecat.core: DEBUG
    org:
      hibernate.orm.jdbc.bind: TRACE  # sql 파라미터 바인딩
      springframework.security: DEBUG

jwt:
  secret: capture_cat_jwt_secret_key_capture_cat_jwt_secret_key
  access-token-expiration: 3600000       # 1시간
  refresh-token-expiration: 604800000    # 7일
