server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 60MB

logging:
  level:
    com.capturecat.core: DEBUG
    org:
      hibernate.orm.jdbc.bind: TRACE
      springframework.security: DEBUG

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000

social:
  api:
    apple:
      token-url: "https://appleid.apple.com/auth/token"
      revoke-url: "https://appleid.apple.com/auth/revoke"
    kakao:
      userinfo-url: "https://kapi.kakao.com/v2/user/me"
      unlink-url: "https://kapi.kakao.com/v1/user/unlink"
